name: Commit Message Check on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 获取所有提交记录以便检查提交信息

      - name: Commit Check Action
        # You may pin to the exact commit or the version.
        # uses: commit-check/commit-check-action@4e3acb738a7f359874cb53ba33ba3f4ea6002c39
        uses: commit-check/commit-check-action@v0.5.1
        with:
          # check commit message formatting convention
          message: true
          # check git branch naming convention
          branch: true
          # check committer author name
          author-name: true
          # check committer author email
          author-email: true
          # check committer commit signature
          commit-signoff: false
          # run checks without failing
          dry-run: true
          # add a job summary
          job-summary: true
