name: Commit Message Check

on:
  push:
    paths:
      - '**.git'

jobs:
  commit-message-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check commit message
      run: |
        COMMIT_MESSAGES=$(git log --format=%B -n 1)

        if [[ ! "$COMMIT_MESSAGES" =~ ^([a-z0-9]+)(\([a-z0-9-]+)\)?:\s(.+)$ ]]; then
          echo "Commit message is invalid"
          exit 1
        fi

        echo "Commit message is valid"
